export const questionBank = [
  {
    id: "algo-binary-search",
    topic: "Algorithms",
    difficulty: "Easy",
    question: "What is the time complexity of binary search on a sorted array?",
    answer: "O(log n)",
    explanation: "Binary search halves the remaining search space on every comparison.",
  },
  {
    id: "algo-merge-sort",
    topic: "Algorithms",
    difficulty: "Medium",
    question: "Why is merge sort guaranteed to run in O(n log n) time?",
    answer: "It divides the array into halves and merges each level in linear time.",
    explanation: "There are log n levels of splitting and each level processes n elements.",
  },
  {
    id: "algo-dp",
    topic: "Algorithms",
    difficulty: "Medium",
    question: "What problem trait makes dynamic programming a good fit?",
    answer: "Overlapping subproblems with optimal substructure.",
    explanation: "DP stores solutions to repeated subproblems and builds toward the optimal whole.",
  },
  {
    id: "algo-greedy",
    topic: "Algorithms",
    difficulty: "Medium",
    question: "What is the main idea behind a greedy algorithm?",
    answer: "Choose the best local option at each step.",
    explanation: "A greedy strategy only works when local choices still lead to a global optimum.",
  },
  {
    id: "algo-bfs",
    topic: "Algorithms",
    difficulty: "Easy",
    question: "Which graph traversal naturally finds the shortest path in an unweighted graph?",
    answer: "Breadth-first search",
    explanation: "BFS explores nodes level by level, so the first time it reaches a node is via the shortest edge count.",
  },
  {
    id: "algo-big-o",
    topic: "Algorithms",
    difficulty: "Easy",
    question: "What does Big-O notation describe?",
    answer: "The upper-bound growth rate of an algorithm.",
    explanation: "It focuses on how time or space grows as input size increases.",
  },
  {
    id: "ds-stack",
    topic: "Data Structures",
    difficulty: "Easy",
    question: "Which access pattern defines a stack?",
    answer: "Last in, first out",
    explanation: "The most recently added item is the first one removed.",
  },
  {
    id: "ds-queue",
    topic: "Data Structures",
    difficulty: "Easy",
    question: "Which access pattern defines a queue?",
    answer: "First in, first out",
    explanation: "The earliest inserted item leaves the structure first.",
  },
  {
    id: "ds-hash-table",
    topic: "Data Structures",
    difficulty: "Medium",
    question: "What is the main purpose of a hash function in a hash table?",
    answer: "Map keys to array indices efficiently",
    explanation: "A good hash spreads keys across buckets to support fast average lookups.",
  },
  {
    id: "ds-tree-height",
    topic: "Data Structures",
    difficulty: "Medium",
    question: "What makes a binary search tree efficient when balanced?",
    answer: "Its height stays near log n",
    explanation: "Operations stay efficient because the search path remains short.",
  },
  {
    id: "ds-linked-list",
    topic: "Data Structures",
    difficulty: "Medium",
    question: "What is a common advantage of a linked list over an array?",
    answer: "Efficient insertions and deletions without shifting elements",
    explanation: "Linked lists can relink nodes instead of moving many values in memory.",
  },
  {
    id: "ds-heap",
    topic: "Data Structures",
    difficulty: "Medium",
    question: "Which operation is a binary heap especially good at?",
    answer: "Repeatedly retrieving the minimum or maximum element",
    explanation: "The heap property keeps the extreme element at the root.",
  },
  {
    id: "os-process-thread",
    topic: "Operating Systems",
    difficulty: "Easy",
    question: "What is the key difference between a process and a thread?",
    answer: "Processes have separate memory spaces, while threads share a process memory space.",
    explanation: "Threads are lighter weight because they share resources inside one process.",
  },
  {
    id: "os-context-switch",
    topic: "Operating Systems",
    difficulty: "Medium",
    question: "What happens during a context switch?",
    answer: "The CPU saves one task state and loads another.",
    explanation: "Registers and scheduling state are swapped so execution can resume later.",
  },
  {
    id: "os-virtual-memory",
    topic: "Operating Systems",
    difficulty: "Medium",
    question: "Why do operating systems use virtual memory?",
    answer: "To give each process an isolated address space and extend usable memory with disk.",
    explanation: "Virtual memory improves safety and lets systems run programs larger than physical RAM.",
  },
  {
    id: "os-deadlock",
    topic: "Operating Systems",
    difficulty: "Hard",
    question: "What is deadlock?",
    answer: "A state where processes wait forever for resources held by each other.",
    explanation: "Circular waiting prevents any of the blocked tasks from moving forward.",
  },
  {
    id: "os-scheduling",
    topic: "Operating Systems",
    difficulty: "Easy",
    question: "What is the goal of CPU scheduling?",
    answer: "Decide which ready task gets CPU time next.",
    explanation: "Schedulers balance responsiveness, throughput, and fairness.",
  },
  {
    id: "os-system-call",
    topic: "Operating Systems",
    difficulty: "Easy",
    question: "What is a system call?",
    answer: "A controlled request for an operating system service.",
    explanation: "Programs use system calls to access files, processes, networking, and devices safely.",
  },
  {
    id: "net-tcp",
    topic: "Networking",
    difficulty: "Easy",
    question: "What is TCP designed to provide that UDP does not?",
    answer: "Reliable, ordered delivery",
    explanation: "TCP adds acknowledgments, retransmissions, and sequencing.",
  },
  {
    id: "net-ip",
    topic: "Networking",
    difficulty: "Easy",
    question: "What is the main responsibility of the IP protocol?",
    answer: "Addressing and routing packets between networks",
    explanation: "IP moves packets across interconnected networks but does not guarantee delivery.",
  },
  {
    id: "net-dns",
    topic: "Networking",
    difficulty: "Easy",
    question: "What problem does DNS solve?",
    answer: "Translating domain names into IP addresses",
    explanation: "Humans remember names more easily than numeric addresses.",
  },
  {
    id: "net-handshake",
    topic: "Networking",
    difficulty: "Medium",
    question: "Why does TCP use a three-way handshake?",
    answer: "To synchronize sequence numbers and confirm both sides are ready.",
    explanation: "The handshake establishes a reliable connection state before data transfer.",
  },
  {
    id: "net-latency",
    topic: "Networking",
    difficulty: "Medium",
    question: "What does latency measure in networking?",
    answer: "How long data takes to travel from sender to receiver",
    explanation: "Lower latency means faster round trips and more responsive systems.",
  },
  {
    id: "net-http",
    topic: "Networking",
    difficulty: "Easy",
    question: "What kind of protocol is HTTP?",
    answer: "An application-layer request-response protocol",
    explanation: "HTTP defines how web clients and servers exchange resources.",
  },
  {
    id: "db-sql-join",
    topic: "Databases",
    difficulty: "Medium",
    question: "What is a SQL join used for?",
    answer: "Combine related rows from multiple tables",
    explanation: "Joins connect data through matching keys.",
  },
  {
    id: "db-primary-key",
    topic: "Databases",
    difficulty: "Easy",
    question: "What is the purpose of a primary key?",
    answer: "Uniquely identify each row in a table",
    explanation: "Primary keys prevent duplicate identities and support relationships.",
  },
  {
    id: "db-index",
    topic: "Databases",
    difficulty: "Medium",
    question: "Why are indexes useful in databases?",
    answer: "They speed up lookups by reducing the amount of scanned data",
    explanation: "Indexes trade extra storage and write cost for faster reads.",
  },
  {
    id: "db-acid",
    topic: "Databases",
    difficulty: "Hard",
    question: "What does the ACID model protect in database transactions?",
    answer: "Correctness and reliability of transactions",
    explanation: "Atomicity, consistency, isolation, and durability help preserve valid data.",
  },
  {
    id: "db-normalization",
    topic: "Databases",
    difficulty: "Medium",
    question: "Why is normalization used in relational design?",
    answer: "Reduce redundancy and update anomalies",
    explanation: "Well-structured tables keep the same fact from being stored inconsistently.",
  },
  {
    id: "db-nosql",
    topic: "Databases",
    difficulty: "Medium",
    question: "When are NoSQL databases often chosen?",
    answer: "When flexible schemas or horizontal scaling are priorities",
    explanation: "Different NoSQL models optimize for large scale and varied data shapes.",
  },
  {
    id: "arch-cache",
    topic: "Computer Architecture",
    difficulty: "Medium",
    question: "Why does a CPU cache improve performance?",
    answer: "It stores frequently used data closer to the processor",
    explanation: "Accessing cache is much faster than reaching main memory.",
  },
  {
    id: "arch-pipeline",
    topic: "Computer Architecture",
    difficulty: "Medium",
    question: "What is instruction pipelining?",
    answer: "Overlapping stages of multiple instruction executions",
    explanation: "Pipelining increases throughput by keeping different hardware stages busy.",
  },
  {
    id: "arch-alu",
    topic: "Computer Architecture",
    difficulty: "Easy",
    question: "What does the ALU do in a processor?",
    answer: "Performs arithmetic and logical operations",
    explanation: "The ALU handles core computations such as addition, comparisons, and bitwise logic.",
  },
  {
    id: "arch-risc-cisc",
    topic: "Computer Architecture",
    difficulty: "Medium",
    question: "What is a common contrast between RISC and CISC designs?",
    answer: "RISC favors simpler instructions, while CISC supports more complex ones.",
    explanation: "The tradeoff affects instruction decoding, optimization, and implementation complexity.",
  },
  {
    id: "arch-ram-rom",
    topic: "Computer Architecture",
    difficulty: "Easy",
    question: "How is RAM different from ROM?",
    answer: "RAM is typically writable volatile memory, while ROM stores persistent firmware data.",
    explanation: "RAM loses data without power, but ROM is meant to retain essential startup instructions.",
  },
  {
    id: "arch-bus",
    topic: "Computer Architecture",
    difficulty: "Easy",
    question: "What is a system bus used for?",
    answer: "Carrying data, addresses, and control signals between components",
    explanation: "It links the CPU, memory, and peripherals into one working system.",
  },
  {
    id: "se-oop",
    topic: "Software Engineering",
    difficulty: "Easy",
    question: "What does encapsulation mean in object-oriented programming?",
    answer: "Bundling data with the methods that operate on it",
    explanation: "Encapsulation hides internal details behind a controlled interface.",
  },
  {
    id: "se-solid",
    topic: "Software Engineering",
    difficulty: "Medium",
    question: "What does the single responsibility principle encourage?",
    answer: "Each module should have one clear reason to change",
    explanation: "Keeping responsibilities narrow makes systems easier to understand and maintain.",
  },
  {
    id: "se-version-control",
    topic: "Software Engineering",
    difficulty: "Easy",
    question: "Why is version control important?",
    answer: "It tracks changes and supports collaboration safely",
    explanation: "Teams can review history, branch work, and recover earlier states.",
  },
  {
    id: "se-testing",
    topic: "Software Engineering",
    difficulty: "Medium",
    question: "What is the purpose of an automated unit test?",
    answer: "Verify a small piece of behavior quickly and repeatedly",
    explanation: "Unit tests catch regressions early and make refactoring safer.",
  },
  {
    id: "se-api",
    topic: "Software Engineering",
    difficulty: "Easy",
    question: "What is an API?",
    answer: "A defined interface for interacting with software components",
    explanation: "APIs specify how one part of a system can request work from another.",
  },
  {
    id: "se-refactor",
    topic: "Software Engineering",
    difficulty: "Medium",
    question: "What is refactoring?",
    answer: "Improving code structure without changing external behavior",
    explanation: "Refactoring makes systems easier to extend and maintain over time.",
  },
];

export const topics = ["All", ...new Set(questionBank.map((card) => card.topic))];
